var top100 = [
  {
    "lead_author":"Lowry_1951",
    "authors":"Lowry, Oh; Rosebrough, Nj; Farr, Al; Randall, Rj",
    "title":"Protein measurement with the folin phenol reagent",
    "journal":"Journal of biological chemistry",
    "pub_year":1951,
    "doi":10001,
    "prizes":"None",
    "discipline":"Biochem",
    "notes":"Number one cited paper for decades"
  },
  {
    "lead_author":"Laemmli_1970",
    "authors":"Laemmli, Uk",
    "title":"Cleavage of structural proteins during assembly of head of bacteriophage-t4",
    "journal":"Nature",
    "pub_year":1970,
    "doi":10001,
    "prizes":"None",
    "discipline":"Biochem",
    "notes":"Also a long-standing classic"
  },
  {
    "lead_author":"Bradford_1976",
    "authors":"Bradford, Mm",
    "title":"Rapid and sensitive method for quantitation of microgram quantities of protein utilizing principle of protein-dye binding",
    "journal":"Analytical biochemistry",
    "pub_year":1976,
    "doi":10001,
    "prizes":"None",
    "discipline":"Biochem",
    "notes":"Replacement' for Lowry, climbed 4th to 3rd since 1987"
  },
  {
    "lead_author":"Sanger_1977",
    "authors":"Sanger, F; Nicklen, S; Coulson, Ar",
    "title":"Dna sequencing with chain-terminating inhibitors",
    "journal":"Proceedings of the national academy of sciences of the united states of america",
    "pub_year":1977,
    "doi":10001,
    "prizes":"Nobel",
    "discipline":"Biochem",
    "notes":"Sanger sequencing - has this dropped off as next gen sequencing to the fore?"
  },
  {
    "lead_author":"Chomczynski_1987",
    "authors":"Chomczynski, P; Sacchi, N",
    "title":"Single-step method of rna isolation by acid guanidinium thiocyanate phenol chloroform extraction",
    "journal":"Analytical biochemistry",
    "pub_year":1987,
    "doi":10001,
    "prizes":"None",
    "discipline":"Biochem",
    "notes":"RNA extraction technique. Why still cite the paper?"
  },
  {
    "lead_author":"Towbin_1979",
    "authors":"Towbin, H; Staehelin, T; Gordon, J",
    "title":"Electrophoretic transfer of proteins from polyacrylamide gels to nitrocellulose sheets - procedure and some applications",
    "journal":"Proceedings of the national academy of sciences of the united states of america",
    "pub_year":1979,
    "doi":10001,
    "prizes":"None",
    "discipline":"Biochem",
    "notes":"The paper that launched the western blot"
  },
  {
    "lead_author":"Lee_1988",
    "authors":"Lee, Ct; Yang, Wt; Parr, Rg",
    "title":"Development of the colle-salvetti correlation-energy formula into a functional of the electron-density",
    "journal":"Physical review b",
    "pub_year":1988,
    "doi":10001,
    "prizes":"None",
    "discipline":"DFT",
    "notes":"TK"
  },
  {
    "lead_author":"Becke_1993",
    "authors":"Becke, Ad",
    "title":"Density-functional thermochemistry .3. the role of exact exchange",
    "journal":"Journal of chemical physics",
    "pub_year":1993,
    "doi":10001,
    "prizes":"None",
    "discipline":"DFT",
    "notes":"B3LYP --- ask friendly guy how to say this."
  },
  {
    "lead_author":"Folch_1957",
    "authors":"Folch, J; Lees, M; Stanley, Ghs",
    "title":"A simple method for the isolation and purification of total lipides from animal tissues",
    "journal":"Journal of biological chemistry",
    "pub_year":1957,
    "doi":10001,
    "prizes":"None",
    "discipline":"Biochem",
    "notes":"Folching - apparently a standard method for lipid extraction from whole tissue, such as the brain"
  },
  {
    "lead_author":"Thompson_1994",
    "authors":"Thompson, Jd; Higgins, Dg; Gibson, Tj",
    "title":"Clustal-w - improving the sensitivity of progressive multiple sequence alignment through sequence weighting, position-specific gap penalties and weight matrix choice",
    "journal":"Nucleic acids research",
    "pub_year":1994,
    "doi":10001,
    "prizes":"None",
    "discipline":"Bioinformatics",
    "notes":"Highest cited bioinformatics paper will be 20 yrs old in Nov"
  },
  {
    "lead_author":"Kaplan_Meier_1958",
    "authors":"Kaplan, El; Meier, P",
    "title":"Nonparametric-estimation from incomplete observations",
    "journal":"Journal of the american statistical association",
    "pub_year":1958,
    "doi":10001,
    "prizes":"None",
    "discipline":"Statistics",
    "notes":"This is a statistical method that is used heavily in biomedicine. Clinical researchers will often provide Kaplan Meier 'curves' or plots of patient survival. http://en.wikipedia.org/wiki/Kaplan%E2%80%93Meier_estimator"
  },
  {
    "lead_author":"Atlschul_1990",
    "authors":"Altschul, Sf; Gish, W; Miller, W; Myers, Ew; Lipman, Dj",
    "title":"Basic local alignment search tool",
    "journal":"Journal of molecular biology",
    "pub_year":1990,
    "doi":10001,
    "prizes":"None",
    "discipline":"Bioinformatics",
    "notes":"BLAST -- should be higher? But so many ways to cite"
  },
  {
    "lead_author":"Sheldrick_2008",
    "authors":"Sheldrick, Gm",
    "title":"Tk",
    "journal":"Acta crystallographica section a",
    "pub_year":2008,
    "doi":10001,
    "prizes":"None",
    "discipline":"Crystallography",
    "notes":"This is really a review paper (open access). It's mindboggling how it got so popular in 6 years. WTF? Probably because the author wrote: \"This paper could serve as a general literature citation when one or more of the open-source SHELX programs (and the Bruker AXS version SHELXTL) are employed in the course of a crystal-structure determination.\" So basically, any crystallographer - anyone working out the structure of small molecules - all started citing this paper for the software they were using. This caused huge amusement in 2010 when the journal briefly shot to 2nd in Thomson Reuters' IF 'science' rankings, ahead of NEJM, Nature, Cell, etc. on the strength of this one paper."
  },
  {
    "lead_author":"Atlschul_1997",
    "authors":"Altschul, Sf; Madden, Tl; Schaffer, Aa; Zhang, Jh; Zhang, Z; Miller, W; Lipman, Dj",
    "title":"Gapped blast and psi-blast: a new generation of protein database search programs",
    "journal":"Nucleic acids research",
    "pub_year":1997,
    "doi":10001,
    "prizes":"None",
    "discipline":"Bioinformatics",
    "notes":"BLAST again �"
  },
  {
    "lead_author":"Murashige_1962",
    "authors":"Murashige, T; Skoog, F",
    "title":"A revised medium for rapid growth and bio assays with tobacco tissue cultures",
    "journal":"Physiologia plantarum",
    "pub_year":1962,
    "doi":10001,
    "prizes":"None",
    "discipline":"Plant sciences",
    "notes":"Kind of a method, but really about the the medium used for plant tissue culture (and I think possibly other types of cell culture). IT's the highest cited plant paper ever, easily!!!"
  },
  {
    "lead_author":"Perdew_1996",
    "authors":"Perdew, Jp; Burke, K; Ernzerhof, M",
    "title":"Generalized gradient approximation made simple",
    "journal":"Physical review letters",
    "pub_year":1996,
    "doi":10001,
    "prizes":"None",
    "discipline":"DFT",
    "notes":"TK"
  },
  {
    "lead_author":"Fulstein_1975",
    "authors":"Folstein, Mf; Folstein, Se; Mchugh, Pr",
    "title":"Mini-mental state - practical method for grading cognitive state of patients for clinician",
    "journal":"Journal of psychiatric research",
    "pub_year":1975,
    "doi":10001,
    "prizes":"None",
    "discipline":"Psychology",
    "notes":"Psychiatric diagnosis"
  },
  {
    "lead_author":"Bligh_1959",
    "authors":"Bligh, Eg; Dyer, Wj",
    "title":"A rapid method of total lipid extraction and purification",
    "journal":"Canadian journal of biochemistry and physiology",
    "pub_year":1959,
    "doi":10001,
    "prizes":"None",
    "discipline":"Biochem",
    "notes":"TK"
  },
  {
    "lead_author":"Southern_1975",
    "authors":"Southern, Em",
    "title":"Detection of specific sequences among dna fragments separated by gel-electrophoresis",
    "journal":"Journal of molecular biology",
    "pub_year":1975,
    "doi":10001,
    "prizes":"None",
    "discipline":"Biochem",
    "notes":"Southern blot"
  },
  {
    "lead_author":"Saitou_1987",
    "authors":"Saitou, N; Nei, M",
    "title":"The neighbor-joining method - a new method for reconstructing phylogenetic trees",
    "journal":"Molecular biology and evolution",
    "pub_year":1987,
    "doi":10001,
    "prizes":"None",
    "discipline":"Organismal bio",
    "notes":"TK"
  },
  {
    "lead_author":"Cox_1972",
    "authors":"Cox, Dr",
    "title":"Regression models and life-tables",
    "journal":"Journal of the royal statistical society series b-statistical methodology",
    "pub_year":1972,
    "doi":10001,
    "prizes":"None",
    "discipline":"Medical statistics",
    "notes":"A foundation document for medical statistics and the insurance industry"
  },
  {
    "lead_author":"Shannon_1976",
    "authors":"Shannon, Rd",
    "title":"Revised effective ionic-radii and systematic studies of interatomic distances in halides and chalcogenides",
    "journal":"Acta crystallographica section a",
    "pub_year":1976,
    "doi":10001,
    "prizes":"None",
    "discipline":"Crystallograpy data",
    "notes":"You could argue that this is the highest-cited database of all time. It is just a massive list of the size of ions in various molecular compounds (oxides and others), with the distances between atoms as well. But it was published as a paper. Nowadays this ought to be in some online database and the compiler would never be cited."
  },
  {
    "lead_author":"Livak_2001",
    "authors":"Livak, Kj; Schmittgen, Td",
    "title":"Analysis of relative gene expression data using real-time quantitative pcr and the 2(t)(-delta delta c) method",
    "journal":"Methods",
    "pub_year":2001,
    "doi":10001,
    "prizes":"None",
    "discipline":"TK",
    "notes":"qPCR method. Why is this so highly cited?"
  },
  {
    "lead_author":"Otwinowski_1997",
    "authors":"Otwinowski, Z; Minor, W",
    "title":"Processing of x-ray diffraction data collected in oscillation mode",
    "journal":"Macromolecular crystallography, pt a",
    "pub_year":1997,
    "doi":10001,
    "prizes":"None",
    "discipline":"Crystallography",
    "notes":"http://www.hkl-xray.com/how-reference-hklhkl-2000' -- asks any publicaton to cite this"
  },
  {
    "lead_author":"Becke_1988",
    "authors":"Becke, Ad",
    "title":"Density-functional exchange-energy approximation with correct asymptotic-behavior",
    "journal":"Physical review a",
    "pub_year":1988,
    "doi":10001,
    "prizes":"None",
    "discipline":"DFT",
    "notes":"Becke again - as top cited paper"
  },
  {
    "lead_author":"Dubois_1956",
    "authors":"Dubois, M; Gilles, Ka; Hamilton, Jk; Rebers, Pa; Smith, F",
    "title":"Colorimetric method for determination of sugars and related substances",
    "journal":"Analytical chemistry",
    "pub_year":1956,
    "doi":10001,
    "prizes":"None",
    "discipline":"Biochem",
    "notes":"TK"
  },
  {
    "lead_author":"Reynolds_1963",
    "authors":"Reynolds, Es",
    "title":"Use of lead citrate at high ph as an electron-opaque stain in electron microscopy",
    "journal":"Journal of cell biology",
    "pub_year":1963,
    "doi":10001,
    "prizes":"None",
    "discipline":"Cell biology",
    "notes":"TK"
  },
  {
    "lead_author":"Thompson_1997",
    "authors":"Thompson, Jd; Gibson, Tj; Plewniak, F; Jeanmougin, F; Higgins, Dg",
    "title":"The clustal_x windows interface: flexible strategies for multiple sequence alignment aided by quality analysis tools",
    "journal":"Nucleic acids research",
    "pub_year":1997,
    "doi":10001,
    "prizes":"None",
    "discipline":"TK",
    "notes":"more sequence alignment"
  },
  {
    "lead_author":"Weber_1969",
    "authors":"Weber, K; Osborn, M",
    "title":"Reliability of molecular weight determinations by dodecyl sulfate-polyacrylamide gel electrophoresis",
    "journal":"Journal of biological chemistry",
    "pub_year":1969,
    "doi":10001,
    "prizes":"None",
    "discipline":"Biochem",
    "notes":"TK"
  },
  {
    "lead_author":"Bland_1986",
    "authors":"Bland, Jm; Altman, Dg",
    "title":"Statistical methods for assessing agreement between two methods of clinical measurement",
    "journal":"Lancet",
    "pub_year":1986,
    "doi":10001,
    "prizes":"None",
    "discipline":"Medical statistics",
    "notes":"TK"
  },
  {
    "lead_author":"Chirgwin_1979",
    "authors":"Chirgwin, Jm; Przybyla, Ae; Macdonald, Rj; Rutter, Wj",
    "title":"Isolation of biologically-active ribonucleic-acid from sources enriched in ribonuclease",
    "journal":"Biochemistry",
    "pub_year":1979,
    "doi":10001,
    "prizes":"None",
    "discipline":"Biochem",
    "notes":"TK"
  },
  {
    "lead_author":"Scratchard_1949",
    "authors":"Scatchard, G",
    "title":"The attractions of proteins for small molecules and ions",
    "journal":"Annals of the new york academy of sciences",
    "pub_year":1949,
    "doi":10001,
    "prizes":"None",
    "discipline":"Biochem",
    "notes":"TK"
  },
  {
    "lead_author":"Baron_1986",
    "authors":"Baron, Rm; Kenny, Da",
    "title":"The moderator mediator variable distinction in social psychological-research - conceptual, strategic, and statistical considerations",
    "journal":"Journal of personality and social psychology",
    "pub_year":1986,
    "doi":10001,
    "prizes":"None",
    "discipline":"Social psychology",
    "notes":"TK"
  },
  {
    "lead_author":"Kohn_1965",
    "authors":"Kohn, W; Sham, Lj",
    "title":"Self-consistent equations including exchange and correlation effects",
    "journal":"Physical review",
    "pub_year":1965,
    "doi":10001,
    "prizes":"Nobel",
    "discipline":"DFT",
    "notes":"Won Nobel prize in 1998 see http://physics.aps.org/story/v2/st19"
  },
  {
    "lead_author":"Mosmann_1983",
    "authors":"Mosmann, T",
    "title":"Rapid colorimetric assay for cellular growth and survival - application to proliferation and cyto-toxicity assays",
    "journal":"Journal of immunological methods",
    "pub_year":1983,
    "doi":10001,
    "prizes":"None",
    "discipline":"Immunology",
    "notes":"TK"
  },
  {
    "lead_author":"Fiske_1925",
    "authors":"Fiske, Ch; Subbarow, Y",
    "title":"The colorimetric determination of phosphorus",
    "journal":"Journal of biological chemistry",
    "pub_year":1925,
    "doi":10001,
    "prizes":"None",
    "discipline":"Biochem",
    "notes":"TK"
  },
  {
    "lead_author":"Iijima_1991",
    "authors":"Iijima, S",
    "title":"Helical microtubules of graphitic carbon",
    "journal":"Nature",
    "pub_year":1991,
    "doi":10001,
    "prizes":"None",
    "discipline":"Nanotubes",
    "notes":"TK"
  },
  {
    "lead_author":"Davis_1964",
    "authors":"Davis, Bj",
    "title":"Disc electrophoresis .2. method and application to human serum proteins",
    "journal":"Annals of the new york academy of sciences",
    "pub_year":1964,
    "doi":10001,
    "prizes":"None",
    "discipline":"Biochem",
    "notes":"TK"
  },
  {
    "lead_author":"Hohenberg_1964",
    "authors":"Hohenberg, P; Kohn, W",
    "title":"Inhomogeneous electron gas",
    "journal":"Physical review b",
    "pub_year":1964,
    "doi":10001,
    "prizes":"(Nobel)",
    "discipline":"DFT",
    "notes":"Early paper"
  },
  {
    "lead_author":"Feinberg_1983",
    "authors":"Feinberg, Ap; Vogelstein, B",
    "title":"A technique for radiolabeling dna restriction endonuclease fragments to high specific activity",
    "journal":"Analytical biochemistry",
    "pub_year":1983,
    "doi":10001,
    "prizes":"None",
    "discipline":"Biochem",
    "notes":"story here: http://garfield.library.upenn.edu/classics1993/A1993KX30900001.pdf"
  },
  {
    "lead_author":"Felsenstein_1985",
    "authors":"Felsenstein, J",
    "title":"Confidence-limits on phylogenies - an approach using the bootstrap",
    "journal":"Evolution",
    "pub_year":1985,
    "doi":10001,
    "prizes":"None",
    "discipline":"Evolution",
    "notes":"TK"
  },
  {
    "lead_author":"Grynkiewicz_1985",
    "authors":"Grynkiewicz, G; Poenie, M; Tsien, Ry",
    "title":"A new generation of ca-2+ indicators with greatly improved fluorescence properties",
    "journal":"Journal of biological chemistry",
    "pub_year":1985,
    "doi":10001,
    "prizes":"Nobel",
    "discipline":"Chemistry",
    "notes":"bio?"
  },
  {
    "lead_author":"OFarrell_1975",
    "authors":"Ofarrell, Ph",
    "title":"High-resolution 2-dimensional electrophoresis of proteins",
    "journal":"Journal of biological chemistry",
    "pub_year":1975,
    "doi":10001,
    "prizes":"None",
    "discipline":"Biochem",
    "notes":"TK"
  },
  {
    "lead_author":"Kresse_1996",
    "authors":"Kresse, G; Furthmuller, J",
    "title":"Efficient iterative schemes for ab initio total-energy calculations using a plane-wave basis set",
    "journal":"Physical review b",
    "pub_year":1996,
    "doi":10001,
    "prizes":"None",
    "discipline":"DFT",
    "notes":"TK"
  },
  {
    "lead_author":"Tamura_2007",
    "authors":"Tamura, K; Dudley, J; Nei, M; Kumar, S",
    "title":"Mega4: molecular evolutionary genetics analysis (mega) software version 4.0",
    "journal":"Molecular biology and evolution",
    "pub_year":2007,
    "doi":10001,
    "prizes":"None",
    "discipline":"Bioinformatics",
    "notes":"secon most recent paper on this list?"
  },
  {
    "lead_author":"Zadeh_1965",
    "authors":"Zadeh, La",
    "title":"Fuzzy sets",
    "journal":"Information and control",
    "pub_year":1965,
    "doi":10001,
    "prizes":"None",
    "discipline":"Artificial intelligence",
    "notes":"This is an important technique in artificial intelligence, used in representing notions like 'hot' that don't have precisely defined boundaries."
  },
  {
    "lead_author":"Sheldrick_1990",
    "authors":"Sheldrick, Gm",
    "title":"Phase annealing in shelx-90 - direct methods for larger structures",
    "journal":"Acta crystallographica section a",
    "pub_year":1990,
    "doi":10001,
    "prizes":"None",
    "discipline":"Crystallography",
    "notes":"TK"
  },
  {
    "lead_author":"Mckhann_1984",
    "authors":"Mckhann, G; Drachman, D; Folstein, M; Katzman, R; Price, D; Stadlan, Em",
    "title":"Clinical-diagnosis of alzheimers-disease - report of the nincds-adrda work group under the auspices of department-of-health-and-human-services task-force on alzheimers-disease",
    "journal":"Neurology",
    "pub_year":1984,
    "doi":10001,
    "prizes":"None",
    "discipline":"Medicine",
    "notes":"ndroduces the most widely used clinical criteria for Alzheimer's. \n http://en.wikipedia.org/wiki/NINCDS-ADRDA_Alzheimer's_Criteria"
  },
  {
    "lead_author":"Burton_1956",
    "authors":"Burton, K",
    "title":"Study of the conditions and mechanism of the diphenylamine reaction for the colorimetric estimation of deoxyribonucleic acid",
    "journal":"Biochemical journal",
    "pub_year":1956,
    "doi":10001,
    "prizes":"None",
    "discipline":"Biochem",
    "notes":"TK"
  },
  {
    "lead_author":"Hamill_1981",
    "authors":"Hamill, Op; Marty, A; Neher, E; Sakmann, B; Sigworth, Fj",
    "title":"Improved patch-clamp techniques for high-resolution current recording from cells and cell-free membrane patches",
    "journal":"Pflugers archiv-european journal of physiology",
    "pub_year":1981,
    "doi":10001,
    "prizes":"None",
    "discipline":"TK",
    "notes":"Notable, at least that this is a neurosci/electrophysiology technique rather than a molecular biology one?"
  },
  {
    "lead_author":"Monkhorst_1976",
    "authors":"Monkhorst, Hj; Pack, Jd",
    "title":"Special points for brillouin-zone integrations",
    "journal":"Physical review b",
    "pub_year":1976,
    "doi":10001,
    "prizes":"None",
    "discipline":"Physics",
    "notes":"TK"
  },
  {
    "lead_author":"Hamilton_1960",
    "authors":"Hamilton, M",
    "title":"A rating scale for depression",
    "journal":"Journal of neurology neurosurgery and psychiatry",
    "pub_year":1960,
    "doi":10001,
    "prizes":"None",
    "discipline":"Depression",
    "notes":"TK"
  },
  {
    "lead_author":"Beck_1961",
    "authors":"Beck, At; Erbaugh, J; Ward, Ch; Mock, J; Mendelsohn, M",
    "title":"An inventory for measuring depression",
    "journal":"Archives of general psychiatry",
    "pub_year":1961,
    "doi":10001,
    "prizes":"None",
    "discipline":"Depression",
    "notes":"TK"
  },
  {
    "lead_author":"Gornall_1949",
    "authors":"Gornall, Ag; Bardawill, Cj; David, Mm",
    "title":"Determination of serum proteins by means of the biuret reaction",
    "journal":"Journal of biological chemistry",
    "pub_year":1949,
    "doi":10001,
    "prizes":"None",
    "discipline":"TK",
    "notes":"TK"
  },
  {
    "lead_author":"Kyte_1982",
    "authors":"Kyte, J; Doolittle, Rf",
    "title":"A simple method for displaying the hydropathic character of a protein",
    "journal":"Journal of molecular biology",
    "pub_year":1982,
    "doi":10001,
    "prizes":"None",
    "discipline":"TK",
    "notes":"TK"
  },
  {
    "lead_author":"Dempster_1977",
    "authors":"Dempster, Ap; Laird, Nm; Rubin, Db",
    "title":"Maximum likelihood from incomplete data via em algorithm",
    "journal":"Journal of the royal statistical society series b-methodological",
    "pub_year":1977,
    "doi":10001,
    "prizes":"None",
    "discipline":"TK",
    "notes":"TK"
  },
  {
    "lead_author":"Metropolis_1953",
    "authors":"Metropolis, N; Rosenbluth, Aw; Rosenbluth, Mn; Teller, Ah; Teller, E",
    "title":"Equation of state calculations by fast computing machines",
    "journal":"Journal of chemical physics",
    "pub_year":1953,
    "doi":10001,
    "prizes":"None",
    "discipline":"TK",
    "notes":"TK"
  },
  {
    "lead_author":"Smith_1985",
    "authors":"Smith, Pk; Krohn, Ri; Hermanson, Gt; Mallia, Ak; Gartner, Fh; Provenzano, Md; Fujimoto, Ek; Goeke, Nm; Olson, Bj; Klenk, Dc",
    "title":"Measurement of protein using bicinchoninic acid",
    "journal":"Analytical biochemistry",
    "pub_year":1985,
    "doi":10001,
    "prizes":"None",
    "discipline":"TK",
    "notes":"TK"
  },
  {
    "lead_author":"Benjamini_1995",
    "authors":"Benjamini, Y; Hochberg, Y",
    "title":"Controlling the false discovery rate - a practical and powerful approach to multiple testing",
    "journal":"Journal of the royal statistical society series b-methodological",
    "pub_year":1995,
    "doi":10001,
    "prizes":"None",
    "discipline":"TK",
    "notes":"TK"
  },
  {
    "lead_author":"Friedewa_1972",
    "authors":"Friedewa, Wt; Fredrick, Ds; Levy, Ri",
    "title":"Estimation of concentration of low-density lipoprotein cholesterol in plasma, without use of preparative ultracentrifuge",
    "journal":"Clinical chemistry",
    "pub_year":1972,
    "doi":10001,
    "prizes":"None",
    "discipline":"TK",
    "notes":"TK"
  },
  {
    "lead_author":"Oldfield_1971",
    "authors":"Oldfield, Rc",
    "title":"The assessment and analysis of handedness: the edinburgh inventory",
    "journal":"Neuropsychologia",
    "pub_year":1971,
    "doi":10001,
    "prizes":"None",
    "discipline":"TK",
    "notes":"TK"
  },
  {
    "lead_author":"Saiki_1988",
    "authors":"Saiki, Rk; Gelfand, Dh; Stoffel, S; Scharf, Sj; Higuchi, R; Horn, Gt; Mullis, Kb; Erlich, Ha",
    "title":"Primer-directed enzymatic amplification of dna with a thermostable dna-polymerase",
    "journal":"Science",
    "pub_year":1988,
    "doi":10001,
    "prizes":"Nobel",
    "discipline":"Biochem",
    "notes":"the paper that describes PCR!"
  },
  {
    "lead_author":"Duncan_1955",
    "authors":"Duncan, Db",
    "title":"Multiple range and multiple f tests",
    "journal":"Biometrics",
    "pub_year":1955,
    "doi":10001,
    "prizes":"None",
    "discipline":"Statistics",
    "notes":"TK"
  },
  {
    "lead_author":"Boyum_1968",
    "authors":"Boyum, A",
    "title":"Isolation of mononuclear cells and granulocytes from human blood - isolation of mononuclear cells by one centrifugation and of granulocytes by combining centrifugation and sedimentation at l g",
    "journal":"Scandinavian journal of clinical & laboratory investigation",
    "pub_year":1968,
    "doi":10001,
    "prizes":"None",
    "discipline":"TK",
    "notes":"TK"
  },
  {
    "lead_author":"Ellman_1959",
    "authors":"Ellman, Gl",
    "title":"Tissue sulfhydryl groups",
    "journal":"Archives of biochemistry and biophysics",
    "pub_year":1959,
    "doi":10001,
    "prizes":"None",
    "discipline":"TK",
    "notes":"TK"
  },
  {
    "lead_author":"Brunger_1998",
    "authors":"Brunger, At; Adams, Pd; Clore, Gm; Delano, Wl; Gros, P; Grosse-Kunstleve, Rw; Jiang, Js; Kuszewski, J; Nilges, M; Pannu, Ns; Read, Rj; Rice, Lm; Simonson, T; Warren, Gl",
    "title":"Crystallography & nmr system: a new software suite for macromolecular structure determination",
    "journal":"Acta crystallographica section d-biological crystallography",
    "pub_year":1998,
    "doi":10001,
    "prizes":"None",
    "discipline":"Crystallography",
    "notes":"TK"
  },
  {
    "lead_author":"Landis_1977",
    "authors":"Landis, Jr; Koch, Gg",
    "title":"Measurement of observer agreement for categorical data",
    "journal":"Biometrics",
    "pub_year":1977,
    "doi":10001,
    "prizes":"None",
    "discipline":"TK",
    "notes":"TK"
  },
  {
    "lead_author":"Dunning_1989",
    "authors":"Dunning, Th",
    "title":"Gaussian-basis sets for use in correlated molecular calculations .1. the atoms boron through neon and hydrogen",
    "journal":"Journal of chemical physics",
    "pub_year":1989,
    "doi":10001,
    "prizes":"None",
    "discipline":"TK",
    "notes":"TK"
  },
  {
    "lead_author":"Novoselov_2004",
    "authors":"Novoselov, Ks; Geim, Ak; Morozov, Sv; Jiang, D; Zhang, Y; Dubonos, Sv; Grigorieva, Iv; Firsov, Aa",
    "title":"Electric field effect in atomically thin carbon films",
    "journal":"Science",
    "pub_year":2004,
    "doi":10001,
    "prizes":"Nobel",
    "discipline":"Graphene",
    "notes":"TK"
  },
  {
    "lead_author":"Laskowski_1993",
    "authors":"Laskowski, Ra; Macarthur, Mw; Moss, Ds; Thornton, Jm",
    "title":"Procheck - a program to check the stereochemical quality of protein structures",
    "journal":"Journal of applied crystallography",
    "pub_year":1993,
    "doi":10001,
    "prizes":"None",
    "discipline":"Crystallography",
    "notes":"TK"
  },
  {
    "lead_author":"Devereux_1984",
    "authors":"Devereux, J; Haeberli, P; Smithies, O",
    "title":"A comprehensive set of sequence-analysis programs for the vax",
    "journal":"Nucleic acids research",
    "pub_year":1984,
    "doi":10001,
    "prizes":"None",
    "discipline":"TK",
    "notes":"TK"
  },
  {
    "lead_author":"Yanischperron_1985",
    "authors":"Yanischperron, C; Vieira, J; Messing, J",
    "title":"Improved m13 phage cloning vectors and host strains - nucleotide-sequences of the m13mp18 and puc19 vectors",
    "journal":"Gene",
    "pub_year":1985,
    "doi":10001,
    "prizes":"None",
    "discipline":"TK",
    "notes":"TK"
  },
  {
    "lead_author":"Ware_1992",
    "authors":"Ware, Je; Sherbourne, Cd",
    "title":"The mos 36-item short-form health survey (sf-36) .1. conceptual-framework and item selection",
    "journal":"Medical care",
    "pub_year":1992,
    "doi":10001,
    "prizes":"None",
    "discipline":"TK",
    "notes":"TK"
  },
  {
    "lead_author":"Akaike_1974",
    "authors":"Akaike, H",
    "title":"New look at statistical-model identification",
    "journal":"Ieee transactions on automatic control",
    "pub_year":1974,
    "doi":10001,
    "prizes":"None",
    "discipline":"TK",
    "notes":"TK"
  },
  {
    "lead_author":"Posada_1998",
    "authors":"Posada, D; Crandall, Ka",
    "title":"Modeltest: testing the model of dna substitution",
    "journal":"Bioinformatics",
    "pub_year":1998,
    "doi":10001,
    "prizes":"None",
    "discipline":"TK",
    "notes":"TK"
  },
  {
    "lead_author":"Hsu_1981",
    "authors":"Hsu, Sm; Raine, L; Fanger, H",
    "title":"Use of avidin-biotin-peroxidase complex (abc) in immunoperoxidase techniques - a comparison between abc and unlabeled antibody (pap) procedures",
    "journal":"Journal of histochemistry & cytochemistry",
    "pub_year":1981,
    "doi":10001,
    "prizes":"None",
    "discipline":"TK",
    "notes":"TK"
  },
  {
    "lead_author":"Dewar_1985",
    "authors":"Dewar, Mjs; Zoebisch, Eg; Healy, Ef; Stewart, Jjp",
    "title":"The development and use of quantum-mechanical molecular-models .76. am1 - a new general-purpose quantum-mechanical molecular-model",
    "journal":"Journal of the american chemical society",
    "pub_year":1985,
    "doi":10001,
    "prizes":"None",
    "discipline":"Quantum chemistry (but not DFT)",
    "notes":"https://en.wikipedia.org/wiki/Austin_Model_1"
  },
  {
    "lead_author":"Kresse_1999",
    "authors":"Kresse, G; Joubert, D",
    "title":"From ultrasoft pseudopotentials to the projector augmented-wave method",
    "journal":"Physical review b",
    "pub_year":1999,
    "doi":10001,
    "prizes":"None",
    "discipline":"DFT",
    "notes":"Another entry in the density functional list: http://en.wikipedia.org/wiki/Projector_augmented_wave_method"
  },
  {
    "lead_author":"Bartlett_1959",
    "authors":"Bartlett, Gr",
    "title":"Phosphorus assay in column chromatography",
    "journal":"Journal of biological chemistry",
    "pub_year":1959,
    "doi":10001,
    "prizes":"None",
    "discipline":"TK",
    "notes":"TK"
  },
  {
    "lead_author":"Jorgensen_1983",
    "authors":"Jorgensen, Wl; Chandrasekhar, J; Madura, Jd; Impey, Rw; Klein, Ml",
    "title":"Comparison of simple potential functions for simulating liquid water",
    "journal":"Journal of chemical physics",
    "pub_year":1983,
    "doi":10001,
    "prizes":"None",
    "discipline":"TK",
    "notes":"TK"
  },
  {
    "lead_author":"Kraulis_1991",
    "authors":"Kraulis, Pj",
    "title":"Molscript - a program to produce both detailed and schematic plots of protein structures",
    "journal":"Journal of applied crystallography",
    "pub_year":1991,
    "doi":10001,
    "prizes":"None",
    "discipline":"Crystallography",
    "notes":"TK"
  },
  {
    "lead_author":"Bondi_1964",
    "authors":"Bondi, A",
    "title":"Van der waals volumes + radii",
    "journal":"Journal of physical chemistry",
    "pub_year":1964,
    "doi":10001,
    "prizes":"None",
    "discipline":"TK",
    "notes":"TK"
  },
  {
    "lead_author":"Ellman_1961",
    "authors":"Ellman, Gl; Courtney, Kd; Andres, V; Featherstone, Rm",
    "title":"A new and rapid colorimetric determination of acetylcholinesterase activity",
    "journal":"Biochemical pharmacology",
    "pub_year":1961,
    "doi":10001,
    "prizes":"None",
    "discipline":"TK",
    "notes":"TK"
  },
  {
    "lead_author":"Moncada_1991",
    "authors":"Moncada, S; Palmer, Rmj; Higgs, Ea",
    "title":"Nitric-oxide - physiology, pathophysiology, and pharmacology",
    "journal":"Pharmacological reviews",
    "pub_year":1991,
    "doi":10001,
    "prizes":"None",
    "discipline":"TK",
    "notes":"TK"
  },
  {
    "lead_author":"Marquardt_1963",
    "authors":"Marquardt, Dw",
    "title":"An algorithm for least-squares estimation of nonlinear parameters",
    "journal":"Journal of the society for industrial and applied mathematics",
    "pub_year":1963,
    "doi":10001,
    "prizes":"None",
    "discipline":"TK",
    "notes":"TK"
  },
  {
    "lead_author":"Kirkpatrick_1983",
    "authors":"Kirkpatrick, S; Gelatt, Cd; Vecchi, Mp",
    "title":"Optimization by simulated annealing",
    "journal":"Science",
    "pub_year":1983,
    "doi":10001,
    "prizes":"None",
    "discipline":"TK",
    "notes":"TK"
  },
  {
    "lead_author":"Blochl_1994",
    "authors":"Blochl, Pe",
    "title":"Projector augmented-wave method",
    "journal":"Physical review b",
    "pub_year":1994,
    "doi":10001,
    "prizes":"None",
    "discipline":"DFT",
    "notes":"An advance in electron structure calculations -- and density functional theory. http://en.wikipedia.org/wiki/Projector_augmented_wave_method"
  },
  {
    "lead_author":"Spurr_1969",
    "authors":"Spurr, Ar",
    "title":"A low-viscosity epoxy resin embedding medium for electron microscopy",
    "journal":"Journal of ultrastructure research",
    "pub_year":1969,
    "doi":10001,
    "prizes":"None",
    "discipline":"TK",
    "notes":"TK"
  },
  {
    "lead_author":"Kresse_1996_2",
    "authors":"Kresse, G; Furthmuller, J",
    "title":"Efficiency of ab-initio total energy calculations for metals and semiconductors using a plane-wave basis set",
    "journal":"Computational materials science",
    "pub_year":1996,
    "doi":10001,
    "prizes":"None",
    "discipline":"DFT",
    "notes":"TK"
  },
  {
    "lead_author":"Birnboim_1979",
    "authors":"Birnboim, Hc; Doly, J",
    "title":"Rapid alkaline extraction procedure for screening recombinant plasmid dna",
    "journal":"Nucleic acids research",
    "pub_year":1979,
    "doi":10001,
    "prizes":"None",
    "discipline":"TK",
    "notes":"TK"
  },
  {
    "lead_author":"Jones_1991",
    "authors":"Jones, Ta; Zou, Jy; Cowan, Sw; Kjeldgaard, M",
    "title":"Improved methods for building protein models in electron-density maps and the location of errors in these models",
    "journal":"Acta crystallographica section a",
    "pub_year":1991,
    "doi":10001,
    "prizes":"None",
    "discipline":"Crystallography",
    "notes":"TK"
  },
  {
    "lead_author":"Berman_2000",
    "authors":"Berman, Hm; Westbrook, J; Feng, Z; Gilliland, G; Bhat, Tn; Weissig, H; Shindyalov, In; Bourne, Pe",
    "title":"The protein data bank",
    "journal":"Nucleic acids research",
    "pub_year":2000,
    "doi":10001,
    "prizes":"None",
    "discipline":"Crystallography",
    "notes":"TK"
  },
  {
    "lead_author":"Perdew_1992",
    "authors":"Perdew, Jp; Wang, Y",
    "title":"Accurate and simple analytic representation of the electron-gas correlation-energy",
    "journal":"Physical review b",
    "pub_year":1992,
    "doi":10001,
    "prizes":"None",
    "discipline":"DFT",
    "notes":"TK"
  },
  {
    "lead_author":"Oregan_1991",
    "authors":"Oregan, B; Gratzel, M",
    "title":"A low-cost, high-efficiency solar-cell based on dye-sensitized colloidal tio2 films",
    "journal":"Nature",
    "pub_year":1991,
    "doi":10001,
    "prizes":"None",
    "discipline":"TK",
    "notes":"TK"
  },
  {
    "lead_author":"Vosko_1980",
    "authors":"Vosko, Sh; Wilk, L; Nusair, M",
    "title":"Accurate spin-dependent electron liquid correlation energies for local spin-density calculations - a critical analysis",
    "journal":"Canadian journal of physics",
    "pub_year":1980,
    "doi":10001,
    "prizes":"None",
    "discipline":"DFT",
    "notes":"TK"
  },
  {
    "lead_author":"Kohler_1975",
    "authors":"Kohler, G; Milstein, C",
    "title":"Continuous cultures of fused cells secreting antibody of predefined specificity",
    "journal":"Nature",
    "pub_year":1975,
    "doi":10001,
    "prizes":"None",
    "discipline":"TK",
    "notes":"TK"
  },
  {
    "lead_author":"Brunauer_1938",
    "authors":"Brunauer, S; Emmett, Ph; Teller, E",
    "title":"Adsorption of gases in multimolecular layers",
    "journal":"Journal of the american chemical society",
    "pub_year":1938,
    "doi":10001,
    "prizes":"None",
    "discipline":"TK",
    "notes":"TK"
  },
  {
    "lead_author":"Ross_1999",
    "authors":"Ross, R",
    "title":"Mechanisms of disease - atherosclerosis - an inflammatory disease",
    "journal":"New england journal of medicine",
    "pub_year":1999,
    "doi":10001,
    "prizes":"None",
    "discipline":"TK",
    "notes":"TK"
  },
  {
    "lead_author":"Matthews_1985",
    "authors":"Matthews, Dr; Hosker, Jp; Rudenski, As; Naylor, Ba; Treacher, Df; Turner, Rc",
    "title":"Homeostasis model assessment - insulin resistance and beta-cell function from fasting plasma-glucose and insulin concentrations in man",
    "journal":"Diabetologia",
    "pub_year":1985,
    "doi":10001,
    "prizes":"None",
    "discipline":"TK",
    "notes":"TK"
  },
  {
    "lead_author":"Ronquist_2003",
    "authors":"Ronquist, F; Huelsenbeck, Jp",
    "title":"Mrbayes 3: bayesian phylogenetic inference under mixed models",
    "journal":"Bioinformatics",
    "pub_year":2003,
    "doi":10001,
    "prizes":"None",
    "discipline":"TK",
    "notes":"TK"
  }
];